/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/_layout_2`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ConstellationView`; params?: Router.UnknownInputParams; } | { pathname: `/../data/quests`; params?: Router.UnknownInputParams; } | { pathname: `/../components/StarEditPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/utils`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/QuestConstellationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/_layout_2`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/types`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ConstellationView`; params?: Router.UnknownOutputParams; } | { pathname: `/../data/quests`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/StarEditPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/utils`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/QuestConstellationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/_layout_2${`?${string}` | `#${string}` | ''}` | `/../lib/types${`?${string}` | `#${string}` | ''}` | `/../components/ConstellationView${`?${string}` | `#${string}` | ''}` | `/../data/quests${`?${string}` | `#${string}` | ''}` | `/../components/StarEditPanel${`?${string}` | `#${string}` | ''}` | `/../lib/utils${`?${string}` | `#${string}` | ''}` | `/../screens/QuestConstellationScreen${`?${string}` | `#${string}` | ''}` | `/app${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/_layout_2`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ConstellationView`; params?: Router.UnknownInputParams; } | { pathname: `/../data/quests`; params?: Router.UnknownInputParams; } | { pathname: `/../components/StarEditPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/utils`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/QuestConstellationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
